services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports: # expose management GUI
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 2s
      timeout: 30s
      retries: 10

  rest-api:
    build:
      context: .
    container_name: rest-api
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy

  processor:
    build:
      context: .
    container_name: processor
    command: ["sh", "start_processors.sh"]
    volumes:
      - .:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    tty: true
    environment:
      - PYTHONUNBUFFERED=1 
